name: Cypress Test Automation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Verify Cypress binary and install if needed
      - name: Verify Cypress Installation
        run: npx cypress install

      # Run Cypress tests
      - name: Run Cypress Tests
        run: npx cypress run
