name: Cypress Test Automation

on:
  workflow_dispatch:

  #push:
   # branches:
    #  - master
  #pull_request:
   # branches:
    #  - master
  # schedule:
    # Run periodically using cron syntax (e.g., every day at midnight UTC)
   # - cron:  '0 */6 * * *'

jobs:
  cypress-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chrome, edge] # Specify the browsers you want to test
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Verify Cypress binary and install if needed
      - name: Verify Cypress Installation
        run: npx cypress install

      # Run Cypress tests in the specified browser
      - name: Run Cypress Tests in ${{ matrix.browser }}
        env:
          CYPRESS_VIDEO: true
          CYPRESS_BROWSER: ${{ matrix.browser }} # Pass the browser to the Cypress CLI
<<<<<<< HEAD
        run: npx cypress run --browser ${{ matrix.browser }} --headed --spec "cypress/e2e/conditional.cy.js" --env ENV=prod
=======
        run: npx cypress run --spec "cypress/e2e/conditional.cy.js" --env ENV=test
>>>>>>> 8f69b8f45a5280254fd17912a46975e7b2c2cea5
