name: Cypress Test Automation

on:
  workflow_dispatch: # Trigger manually

jobs:
  cypress-tests:
    runs-on: windows-latest
    strategy:
      fail-fast: false # Allow all tests to run even if one fails
      matrix:
        browser: [chrome] # Define browsers for testing
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Cache Node.js dependencies to speed up workflow
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies using cached data if available
      - name: Install Dependencies
        run: npm ci

      # Verify Cypress installation
      - name: Verify Cypress Installation
        run: npx cypress verify

      # Run Cypress tests
      - name: Run Cypress Tests in ${{ matrix.browser }}
        env:
          CYPRESS_VIDEO: false
          CYPRESS_BROWSER: ${{ matrix.browser }}
        run: npx cypress run --browser ${{ matrix.browser }} --spec "cypress/e2e/Trademark Bridge/env_conditional_trademark_bridge.cy.js"
