name: Cypress Test Automation

on:
  push:
    branches:
      - master # Run when commits are pushed to the master branch
  pull_request:
    branches:
      - master # Run when a pull request is made to the master branch
  schedule:
    # Run periodically using cron syntax (e.g., every day at midnight UTC)
    - cron:  '0 */6 * * *'

jobs:
  cypress-tests:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Verify Cypress binary and install if needed
      - name: Verify Cypress Installation
        run: npx cypress install

      # Run Cypress tests
      - name: Run Cypress Tests
        run: npx cypress run
